[package]
name = "photonic-console"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]
edition = "2018"

[dependencies]
photonic-core = {path="../photonic-core"}
palette = "0.4"
failure = "0.1"
serde = { version = "1", features = ["derive"] }
