[package]
name = "photonic-interface-grpc"

version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
photonic = { workspace = true }
photonic-interface-grpc-proto = { path = "./proto" }

palette = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }

tonic = {version = "0.11"}
prost = "0.12"
prost-types = "0.12"
