[package]
name = "photonic-core"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]
edition = "2018"

[dependencies]
palette = "0.4"
regex = "0.2"
failure = "0.1"
rand = "0.6"
num = "0.2"
ezing = "0.2"

[dev-dependencies]
assert_approx_eq = "1"
