[workspace]
members = [
    "photonic-core",
    "photonic-console",
    "photonic-effects",
    "photonic-net",
    "photonic-mqtt",
    "photonic-rpi",
    "photonic-exec",
    "photonic-grpc",
    "photonic-grpc-proto",
    "photonic-varlink",
    "photonic-cli",
    "photonic",
    "examples",
]
