[workspace]
members = [
    "photonic-core",
    "photonic-console",
    "photonic-effects",
    "photonic-net",
    "photonic-mqtt",
    "photonic-ledstrip",
    "photonic-exec",
    "photonic-grpc",
    "photonic-grpc-proto",
    "photonic-cli",
    "photonic-run",
    "photonic-dyn",
    "examples",
]
