[package]
name = "photonicd"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]
edition = "2018"

[dependencies]
failure = "0.1"
num = "*"
rand = "*"
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
photonic = { path = "../photonic" }
photonic_derive = { path = "../photonic_derive" }
photonic_proto = { path = "../photonic_proto" }
ws = "0.7"
clap = "2"
ezing = "0.2"
