[package]
name = "photonic-exec"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]
edition = "2018"

[dependencies]
photonic-core = {path="../photonic-core"}
anyhow = "1"
shlex = "1"
shared_memory = "0.12.0"
byteorder = "1.3"
