[package]
name = "photonic-interface-grpc-client"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true

[dependencies]
photonic-interface-grpc-proto = { version = "0.1.0", path = "../proto", features = ["client"] }

anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
palette = { workspace = true }

tonic = "0.12.2"

yansi = "1.0"
askama = "0.12"

reedline-repl-rs = { version = "1.1.1", features = ["derive", "async"] }
clap = { version = "4.5.4", features = ["derive", "cargo"] }

[lints]
workspace = true
