[package]
name = "photonic-interface-grpc-client"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
python = ["dep:pyo3"]

[dependencies]
photonic-interface-grpc-proto = { version = "0.1.0", path = "../proto", features = ["client"] }

anyhow = { workspace = true }
palette = { workspace = true }

tonic = "0.14.0"

parking_lot = { version = "0.12.3", features = ["arc_lock", "send_guard"] }

pyo3 = { version = "0.26", optional = true, features = ["extension-module", "anyhow", "experimental-async"] }

static_assertions = "1.1.0"

[lints]
workspace = true
