[package]
name = "photonic-rpi"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]
edition = "2018"

[dependencies]
photonic-core = {path="../photonic-core"}
palette = "0.4"
anyhow = "1"

[target.'cfg(target = "arm-unknown-linux-gnueabihf")'.dependencies]
rs_ws281x = "0.2.3"
