[package]
name = "photonic-dyn-derive"

version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "photonic_app_derive"
proc-macro = true

[dependencies]
proc-macro2 = { version = "1", features = ["proc-macro"] }
quote = { version = "1", features = ["proc-macro"] }
syn = { version = "2", features = [ "full", "extra-traits", "clone-impls", "derive", "parsing", "printing", "proc-macro"] }
darling = { version = "0.20", features = ["suggestions", "diagnostics"]}
