[package]
name = "photonic"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]
edition = "2018"

[dependencies]
regex = "0.2"
scarlet = "1"
failure = "0.1"
rand = "*"

[dev-dependencies]
assert_approx_eq = "1"
