[package]
name = "photonic-interface-grpc-proto"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true

[features]
server = []
client = []

[dependencies]
tonic = "0.14.2"
tonic-prost = "0.14.2"
prost = "0.14.1"

[build-dependencies]
tonic-prost-build = { version = "0.14.2" }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["prost", "tonic-prost"]

