[package]
name = "example"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]
edition = "2018"

[dependencies]
photonic-core = {path="../photonic-core"}
photonic-mqtt = {path="../photonic-mqtt"}
photonic-net = {path="../photonic-net"}
photonic-console = {path="../photonic-console"}
photonic-effects = {path="../photonic-effects"}
photonic-ledstrip = {path= "../photonic-ledstrip" }
photonic-exec = {path="../photonic-exec"}
photonic-grpc = {path="../photonic-grpc"}
anyhow = "1"
shared_memory = "0.11.4"
byteorder = "1.3"
tokio = { version = "1.1.1", features = [ "rt-multi-thread" ] }
