[package]
name = "photonic-effects"

version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
photonic = { workspace = true }
photonic-dyn = { path = "../dyn" }

futures = { workspace = true }

anyhow = { workspace = true }
palette = { workspace = true, features = ["serializing"] }
rand = { workspace = true }
num-traits = { workspace = true }
noise = { workspace = true }

ezing = "0.2"
serde = { version = "1.0.196", features = ["derive"] }
