[package]
name = "photonic-effects"

version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
photonic = { workspace = true }

anyhow = { workspace = true }
palette = { workspace = true }
rand = { workspace = true }
num-traits = { workspace = true }

ezing = "0.2"
noise = "0.8"
