[package]
name = "photonic-effects"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]
edition = "2018"

[dependencies]
photonic-core = {path="../photonic-core"}
anyhow = "1"
rand = "0.8"
num = "0.4"
noise = "0.7"
serde = { version = "1", features = ["derive"] }
