[package]
name = "photonic-effects"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]
edition = "2018"

[dependencies]
photonic-core = {path="../photonic-core"}
failure = "0.1"
rand = "0.6"
num = "0.2"
noise = "0.5"
