[package]
name = "photonic-dynamic-boxed"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
palette = { workspace = true }
anyhow = { workspace = true }

photonic = { path = "../../core" }

async-trait = { workspace = true }
