[package]
name = "photonic-dyn-runner"

version.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "photonic"
path = "src/main.rs"

[dependencies]
photonic = { workspace = true }
photonic-dyn = { path = ".." }
photonic-effects = { path = "../../effects" }
photonic-output-terminal = { path = "../../output-terminal" }

anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
serde_dhall = "0.12"
toml = "0.8"
ron = "0.8"

clap = { version = "4.5.4", features = ["derive"] }