[package]
name = "photonic-mqtt"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]
edition = "2018"

[dependencies]
photonic-core = {path="../photonic-core"}
anyhow = "1"
mqtt-async-client = "0.2.0"
async-trait = "0.1.48"
serde_json = "1.0.64"
