[package]
name = "photonic-interface-grpc-cli"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true

[dependencies]
photonic-interface-grpc-client = { version = "0.1.1", path = "../client" }

anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
itertools = { workspace = true }

yansi = "1.0"

reedline-repl-rs = { version = "1.1.1", features = ["async_derive", "async", "shlex"] }
clap = { version = "4.5.4", features = ["derive", "cargo"] }

[lints]
workspace = true
