[package]
name = "photonic_derive"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version="0.15", features=["extra-traits"]}
quote ="0.6"
